name: Daily Stock Report

# This tells GitHub Actions to trigger the workflow at 9 AM every day
on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 09:00 AM CET (UTC+2) every day
  workflow_dispatch:      # This enables the manual trigger

jobs:
  build:
    runs-on: ubuntu-latest # Linux operating system as runner environment
    permissions:
      contents: write     # Add permission to write to repository

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install ffn pandas matplotlib plotly
          pip install jupyter notebook nbformat pyyaml ipykernel

      # Step 4: Run the Python script to generate CSV
      - name: Run extract_data.py
        run: python extract_data.py

      # Step 6: Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 7: Render Quarto Project
      - name: Render Quarto Project
        run: quarto render

      # Step 8: Configure Git and commit changes
      - name: Configure Git and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/*.csv
          git add docs/*  # Add the rendered Quarto site in docs folder
          git commit -m "Update stock data and plot $(date +'%Y-%m-%d')"
          git push

      # Step 9: Upload CSV as artifacts (as backup)
      - name: Upload CSV and plot as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stock-data-reports
          path: |
            data/*.csv